version: "3.8"

services:
  backend:
    build: ./be/be_web
    container_name: springboot-app
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mainline.proxy.rlwy.net:37611/railway?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: XgXLVQaFzOBKyhRVSYOXQqcLyyXxjGvT
    restart: always

  frontend:
    build: ./fe/frontend_web
    container_name: react-app
    ports:
      - "3000:3000"
    restart: always
    depends_on:
      - backend
